name: Deploy to Preview Channel

on:
  pull_request:
      branches: [ "main" ]
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    steps:
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
