- name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
        node-version: [18.x]
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@main
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN}}