name: Firebase CI

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm i
    - run: npm install -g firebase-tools
    - run: npm run test
    - run: npm run build
    - name: Archive Build
      uses: actions/upload-artifact@main
      with:
        name: build
        path: public

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Download Build
        uses: actions/download-artifact@main
        with:
          name: build
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}